/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.furb.view;

import br.furb.lib.NumberedBorder;

/**
 *
 * @author flavioomar
 */
public class CompiladorView extends javax.swing.JFrame {

    /**
     * Creates new form CompiladorView
     */
    public CompiladorView() {
        initComponents();
        this.editorTA.setBorder(new NumberedBorder());
        this.setSize(914, 627);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        principalJP = new javax.swing.JPanel();
        toolBarJP = new javax.swing.JPanel();
        barraFerramentaTB = new javax.swing.JToolBar();
        editorJP = new javax.swing.JPanel();
        editorJSP = new javax.swing.JScrollPane();
        editorTA = new javax.swing.JTextArea();
        mensagemJP = new javax.swing.JPanel();
        mensagemJSP = new javax.swing.JScrollPane();
        mensagemTA = new javax.swing.JTextArea();
        statusJP = new javax.swing.JPanel();
        statusJL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(914, 627));
        setPreferredSize(new java.awt.Dimension(914, 627));
        setSize(new java.awt.Dimension(914, 627));

        principalJP.setLayout(new java.awt.GridBagLayout());

        toolBarJP.setMinimumSize(new java.awt.Dimension(144, 544));
        toolBarJP.setPreferredSize(new java.awt.Dimension(144, 544));
        toolBarJP.setLayout(new java.awt.BorderLayout());

        barraFerramentaTB.setFloatable(false);
        barraFerramentaTB.setOrientation(javax.swing.SwingConstants.VERTICAL);
        barraFerramentaTB.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        barraFerramentaTB.setMinimumSize(new java.awt.Dimension(144, 544));
        barraFerramentaTB.setPreferredSize(new java.awt.Dimension(144, 544));
        toolBarJP.add(barraFerramentaTB, java.awt.BorderLayout.EAST);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 0.88;
        principalJP.add(toolBarJP, gridBagConstraints);

        editorJP.setMinimumSize(new java.awt.Dimension(750, 480));
        editorJP.setPreferredSize(new java.awt.Dimension(750, 480));
        editorJP.setLayout(new java.awt.BorderLayout());

        editorJSP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        editorJSP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        editorJSP.setMinimumSize(new java.awt.Dimension(750, 480));
        editorJSP.setPreferredSize(new java.awt.Dimension(750, 480));

        editorTA.setColumns(20);
        editorTA.setRows(5);
        editorJSP.setViewportView(editorTA);

        editorJP.add(editorJSP, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.83;
        gridBagConstraints.weighty = 0.77;
        principalJP.add(editorJP, gridBagConstraints);

        mensagemJP.setMinimumSize(new java.awt.Dimension(750, 90));
        mensagemJP.setPreferredSize(new java.awt.Dimension(750, 90));
        mensagemJP.setLayout(new java.awt.BorderLayout());

        mensagemJSP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        mensagemJSP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        mensagemJSP.setMinimumSize(new java.awt.Dimension(750, 90));
        mensagemJSP.setPreferredSize(new java.awt.Dimension(750, 90));

        mensagemTA.setEditable(false);
        mensagemTA.setColumns(20);
        mensagemTA.setRows(5);
        mensagemJSP.setViewportView(mensagemTA);

        mensagemJP.add(mensagemJSP, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.83;
        gridBagConstraints.weighty = 0.14;
        principalJP.add(mensagemJP, gridBagConstraints);

        statusJP.setMinimumSize(new java.awt.Dimension(900, 25));
        statusJP.setPreferredSize(new java.awt.Dimension(900, 25));
        statusJP.setLayout(new java.awt.BorderLayout());

        statusJL.setText("jLabel1");
        statusJL.setMinimumSize(new java.awt.Dimension(900, 25));
        statusJL.setPreferredSize(new java.awt.Dimension(900, 25));
        statusJP.add(statusJL, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.04;
        principalJP.add(statusJP, gridBagConstraints);

        getContentPane().add(principalJP, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompiladorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompiladorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompiladorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompiladorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompiladorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraFerramentaTB;
    private javax.swing.JPanel editorJP;
    private javax.swing.JScrollPane editorJSP;
    private javax.swing.JTextArea editorTA;
    private javax.swing.JPanel mensagemJP;
    private javax.swing.JScrollPane mensagemJSP;
    private javax.swing.JTextArea mensagemTA;
    private javax.swing.JPanel principalJP;
    private javax.swing.JLabel statusJL;
    private javax.swing.JPanel statusJP;
    private javax.swing.JPanel toolBarJP;
    // End of variables declaration//GEN-END:variables
}
